### ISSUE TITLE
Final Project Proposal

### ISSUE THREAD

**Issue by rohjs** [sisobus/WebStudio2019#100]
# Automated Portfolio

## 1. Purpose

> "아, 포트폴리오 업데이트 해야하는데...."

라고 다짐만 한 지 2년 째.
누군가 포트폴리오를 요청할 때마다 부끄러워지는 것도 이젠 지겹습니다.

#### Why I haven't updated my portfolio

* 노예는 돈을 벌어야 한다 (시간 부족)
* 글쓰는 걸 병적으로 싫어한다
* 귀차니즘
* 정리정돈이 참 어려운 사람
* 그런데 쓸데없는 완벽주의적 경향

#### Solution

포폴에 작품에 관한 글을 작성하고, 관련 이미지를 올리고, 디플로이까지 하는 과정을 **매우 쉽고 간단하게** 만든다. 그래서 이 마저도 하지 않는 나 자신을 발견할 때  스스로 **자괴감이 들게 만든다.**

## 2. Specifications

1. React, NextJS
2. _TypeScript?_
3. Node.js
4. now.sh
5. @emotionjs
6. Webpack
7. LaxJS?
8. remark.js

## 3. To do list

- [x] Design
- [ ] Style react components
- [x] Implement Node script that renders markdown contents into React component
  - [x] Use `remarkjs` to generate `md` to `html` strings
  - [x] Pass the rendered result using `dangerouslyInnerHTML` 
- [ ] Implement a script that extracts `yaml` from `md` and generate `json` file _(Not Sure)_
- [x] Create a deploy script
- [ ] Create a making film for youtube _(If I have time)_

**Comment by sisobus** [comment]
과연 성공할것인가

**Comment by rohjs** [comment]
이미 성공했습니다 훗
나머지는 Piece of cake you know~
