### ISSUE TITLE
AttributeError: 'function' object has no attribute 'get_json'

### ISSUE THREAD

**Issue by ksdjx1** [sisobus/WebStudio2019#109]
AttributeError: 'function' object has no attribute 'get_json'
갑자기 이런 에러가 나네요;;;
저번에 만지고 나서 처음 만지는건데 
뭐가 문젤까요...ㅜㅜ

**Comment by sisobus** [comment]
In Flask/wrappers.py the method get_json() is defined as method to the class Request.

However, the same file still contains the old, deprecated method json(). If you have an old version of flask, then a) update or b) use request.json() instead.
