### ISSUE TITLE
syncing Upstream fork

### ISSUE THREAD

**Issue by wakii** [sisobus/WebStudio2019#15]
안녕하세요. 

https://help.github.com/en/articles/syncing-a-fork
교수님 repository을 월요일날 Fork해서 제 repository에 복사하고, 교수님께서 업데이트 된 내용을 오늘 제 repository에도 업데이트하려고 저 게시물을 찾아봤습니다.

저 게시물 내용에 따라 fork 후 clone된 제 local repository에 들어간 후(WebStudio2019)
git fetch upstream을 시도해봤는데 
```
`fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`
```

라고 뜨고 안되네요. 

어떻게 sync 하나요???

**Comment by sisobus** [comment]
와 좋은 시도네요!
사실 저걸 이용해서 fork한 repository와 원래 repository의 sync맞추는 걸 넣어야지 넣어야지 하다가 잊고 못 넣은 내용이에요.

>
>[https://help.github.com/en/articles/syncing-a-fork](https://help.github.com/en/articles/syncing-a-fork)
>

언급하신 저 글을 조금만 더 자세히 읽었으면 해결했을 거라 생각됩니다. 첫째줄에 써있는 다음 문장을 먼저 해야해요.

>
>Before you can sync your fork with an upstream repository, you must [configure a remote that points to the upstream repository](https://help.github.com/en/articles/configuring-a-remote-for-a-fork) in Git.
>
