### ISSUE TITLE
Which branch pulled?

### ISSUE THREAD

**Issue by wakii** [sisobus/WebStudio2019#16]
안녕하세요.

실습 내용 중에 파일 작성을 1-practice-<자기이름> 라는 브랜치에서 한 후, 그러고 나서 add, commit, pull 또한 같은 브랜치에서 이뤄진 것을 fork 한 제 remote repository에서 확인하였습니다.

이 브랜치만 pull request 된 건가요??
master branch의 경우는 어떻게 되는 건가요??

제 remote repository 내에서도 새로만든 branch로 들어가야만 만들었던 파일이 확인이 되서 궁금합니다!

**Comment by sisobus** [comment]
맞습니다. 
브랜치를 새로 파서 작업을 했기 때문에, local repository의 master는 맨 처음 clone 떴을 때와 변함이 없을거에요.
이 경우 두가지 방법이 있는데,

1. fork 한 본인의 remote repository에 pull requests를 날리는 방법
2. git merge를 이용하는 방법

2번은 안배웠고 1번은 github에서 클릭으로 할 수 있으니까 아마 1번이 더 쉽지 않을까 생각이 드는데요, 둘다 적어둘게요.

1. fork 한 본인의 remote repository에 pull requests를 날리는 방법
1-1. pull requests를 날릴 때, 원본 유저쪽 말고 본인 repository/master 로 설정하고 pull requests
1-2. pull requests란에 들어가서 merge (이러면 master로 merge됨)
1-3. local repository에서 git pull origin master

2. local에서 git merge를 이용하는 방법
2-1. git checkout master
2-2. git merge branch-name
2-3. git push origin master
