### ISSUE TITLE
fork한 repository 싱크 맞추기

### ISSUE THREAD

**Issue by ksdjx1** [sisobus/WebStudio2019#17]
저번에 싱크를 맞추고 다시 맞춰보려고 했는데요!

macui-MacBook-Pro-2:webstudio2019 Kang$ git remote -v
origin	https://github.com/ksdjx1/WebStudio2019.git (fetch)
origin	https://github.com/ksdjx1/WebStudio2019.git (push)
upstream	https://github.com/sisobus/webstudio2019.git (fetch)
upstream	https://github.com/sisobus/webstudio2019.git (push)
macui-MacBook-Pro-2:webstudio2019 Kang$ git remote add upstream https://github.com/sisobus/webstudio2019.git
fatal: remote upstream already exists.

이 경우 업데이트 파일이 존재하기 때문에 안 되는 것인지
혹은 싱크가 전부 맞기 때문에 안 되는 것인지
궁금합니다!

(바쁘시면 천천히 답변 주셔도 괜찮습니당)

**Comment by ksdjx1** [comment]
잘못 올렸네요 잠시만용

**Comment by sisobus** [comment]
앗 upstream이 이미 존재하네요 

> [https://help.github.com/en/articles/syncing-a-fork](https://help.github.com/en/articles/syncing-a-fork)

이거 3번부터 하시면 될 것 같습니다
