### ISSUE TITLE
curl using

### ISSUE THREAD

**Issue by junoflow** [sisobus/WebStudio2019#42]
Windows OS의 개인 컴퓨터를 사용하여 ubuntu로 코딩을 했는데 local에서 작업 후 python answer.py를 돌리고 curl로 테스트를 해보려고 하니 Failed to connect to 54.180.96.144 port 5002: Connection refused 라고 나옵니다.

그래서 ssh로 54.180.96.144에 접속해서 똑같이 python answer.py를 돌리고 curl로 테스트를 해보니 이건 잘 됩니다. (랩실 제 자리가 pip가 제대로 작동되지 않아 계속 서버에서 작업했었습니다.)

제가 curl에 대한 이해가 부족한건지(원래 외부서버 접속 후 해야 되는건지), 아니면 세팅 차이 때문인건지 여쭤보고싶습니다.

**Comment by sisobus** [comment]
curl 54.180.96.144:5002/api/users 비슷하게 썼을 것 같은데 ..
54.180.96.144는 실습서버 주소여서, 본인 컴퓨터위에 flask server를 켰다면
본인 컴퓨터의 ip주소를 써줘야 합니다.

curl 0.0.0.0:5002/api/users 이렇게 하면 될 것 같습니다 ㅎㅎ
