### ISSUE TITLE
Impassion 웹페이지

### ISSUE THREAD

**Issue by Lena1127** [sisobus/WebStudio2019#76]
제가 이번학기동안 제작하려고 하는 프로젝트는 현재 활동하고 있는 연합동아리 Impassion의 공식 웹입니다. 

밑에와 같은 세가지 카테고리를 만들려고 합니다. 
About us - The Team : 임패션 동아리 소개
                - I'mpassioner : 동아리원 소개 (사진, 소개글 업로드)
Regular Session - 매주 동아리 활동시 진행하는 주제 ppt, 활동 정리를 업로드 할 수 있도록 합니다.  
Open Session - 한학기에 한번 있는 오픈 세션 때 진행하는 주제, 발표자료, 사진, 소감등을 업로드 할 수 있도록 합니다.

**Comment by sisobus** [comment]
와 엄청 좋네요
사진이나 파일 업로드를 구현하는게 조금 힘들 것 같은데, 같이 열시미 만들어봅시다
