### ISSUE TITLE
20121154 김서하

### ISSUE THREAD

**Issue by SeohaKim** [sisobus/WebStudio2019#77]
# 보드게임 플래너
인원, 시간, 멍청한 정도, 서로 싫어하는 정도를 기입하면 보드게임 플랜을 짜주는 간단한 1페이지 앱

![UPAD_Images_20190520_201530](https://user-images.githubusercontent.com/32384961/58017800-10b40c00-7b3c-11e9-9af1-19bbe84211da.jpg)

**Comment by sisobus** [comment]
오 어떤 방식으로 플랜을 짜줄지 궁금하네요
