### ISSUE TITLE
페이지 구상

### ISSUE THREAD

**Issue by yeongmo-j** [sisobus/WebStudio2019#78]
<img width="602" alt="스크린샷 2019-05-20 오후 8 18 34" src="https://user-images.githubusercontent.com/40863564/58017990-946df880-7b3c-11e9-823d-adc05ed0ee32.png">

**Comment by sisobus** [comment]
와 .. 피피티로 작성한건가요 멋지네용

**Comment by yeongmo-j** [comment]
앗 감사합니다
