### ISSUE TITLE
독서 관리 웹

### ISSUE THREAD

**Issue by geronimo03** [sisobus/WebStudio2019#79]
독서 기록을 PC로도 관리할 수 있었으면 좋겠다는 아이디어가 있었어요

독서 기록:
Read Unread Wishlist
책표지 이미지를 활용한 책 목록 작성
Csv 추출, Google 문서 동기화
리뷰와 별점 주기 가능

**Comment by sisobus** [comment]
아주 좋습니다 !! 조금 어려워보이는데, 쉬운기능부터 차근차근 구현해봅시다
