### ISSUE TITLE
파이널 프로젝트

### ISSUE THREAD

**Issue by ssora09** [sisobus/WebStudio2019#81]
<개인 포트폴리오 사이트>
<img width="989" alt="스크린샷 2019-05-20 오후 8 45 19" src="https://user-images.githubusercontent.com/32293633/58019381-5a9ef100-7b40-11e9-8ea0-60d3c3c65611.png">

간단한 첫 페이지 레이아웃만 구상해보았습니다.
개인 포트폴리오 사이트 제작을 고민중입니다.

**Comment by sisobus** [comment]
무난하네요 !! 일단 만들어보고 발전시켜봅시다
