### ISSUE TITLE
프로젝트 구상

### ISSUE THREAD

**Issue by Baehatricespare** [sisobus/WebStudio2019#82]
전 무난하게 포트폴리오 사이트를 만드려구합니당 
대신 뭔가 각 작품에 비밀 댓글? 제 이메일로 댓글을 보낼 수 있는 기능? 을 넣어서
어떤 작품을 보고 연락했는지 알 수 있도록 하는게 목표입니당

![포폴](https://user-images.githubusercontent.com/32293555/58019368-5541a680-7b40-11e9-8171-085fe6614889.png)

**Comment by sisobus** [comment]
비밀기능!! 좋습니다 관리자, 당사자만 볼 수 있도록 하면 되겠네요!
