### ISSUE TITLE
파이널 프로젝트 기획

### ISSUE THREAD

**Issue by JihyunLee27** [sisobus/WebStudio2019#84]
[SmileySmiley기획서.pdf](https://github.com/sisobus/WebStudio2019/files/3197754/SmileySmiley.pdf)

**Comment by JihyunLee27** [comment]
![image](https://user-images.githubusercontent.com/48281371/58019892-9090a500-7b41-11e9-8e6a-e9ca01727bf7.png)

**Comment by sisobus** [comment]
이미 머리속에 얼추 구현이 되어 있는 것 같네요 ㅎㅎ좋습니다!!
