### ISSUE TITLE
웹 게임

### ISSUE THREAD

**Issue by ksdjx1** [sisobus/WebStudio2019#85]
웹 상에서 게임을 구현하고자 함.
유저 ID-Password를 받아 지속적인 계정 사용이 가능하게 함.
게임 승-패에 따른 랭크를 메기고 친구추가 기능까지 구현하려고 함.

게임 내용 - 유저 두 명을 랜덤하게 배정하여 매칭, 채팅을 기반으로 진행함.
게임에 들어간 각 유저는 각각 한 단어를 배정받게 되며, 해당 단어를 상대방이 언급할 경우 승리.
대화를 이루어가면서 어떻게 해당 단어로 유도해 갈 것인가가 포인트.

기존 랜덤채팅에 조금 더 흥미요소를 첨가하고 싶었음.
지속가능한 웹 게임 서비스를 목표로 함.

**Comment by sisobus** [comment]
websocket, socketio를 잘 활용해봅시다!
