### ISSUE TITLE
파이널 프로젝트 계획

### ISSUE THREAD

**Issue by jindogliani** [sisobus/WebStudio2019#86]
[포트폴리오사이트기획서.pdf](https://github.com/sisobus/WebStudio2019/files/3198383/default.pdf)

안녕하세요.

포트폴리오 사이트를 만드는데
백엔드를 쓴다면 유저가 좌표를 찍어서 그 좌표에 코멘트나 피드백을 남기는 기능을 추가하고 싶습니다.

**Comment by sisobus** [comment]
와 좌표에 코멘트나 피드백.. !! 조금 어려워보이지만 할 수 있습니다 화이팅!
